### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by Sevitas** [kontent-ai/management-sdk-net#197]
### Motivation

Allow users to send custom headers in each request - or at least to add the option to include a tracking header.

This will help us to track the usage of the tools using the SDK - specifically the .NET model generator tool.

**Comment by Simply007** [comment]
Mind also this possibility in Delivery SDK .NET: https://github.com/kontent-ai/delivery-sdk-net/pull/237

**Comment by Simply007** [comment]
It might be one of the candidates for "Core" package unification.

**Comment by Simply007** [comment]
Ready for merge and release
