### ISSUE TITLE
Add support for Collection property in Assets

### ISSUE THREAD

**Issue by AdamZ-Kontent** [kontent-ai/management-sdk-net#245]
### Motivation

New collection property will be added to the Asset models in management api, this SDK should support it too.
The property will be nullable and at first be hidden behind a feature toggle and accessible only to customers that wish to participate in early access.

### Proposed solution

Extend Asset models with a new Collection reference property

### Additional context

early access release date: 14.6.2023
[docs](https://kontent.ai/learn/reference/openapi/management-api-v2/#section/Asset-object)
the new Collection property will be an object containing a nullable reference to a collection
example of the property in json:  
`"collection": {
       "reference": { "id": "00000000-0000-0000-0000-000000000000" }
  }`

**Comment by Simply007** [comment]
Fixed in #248
