### ISSUE TITLE
EnvironmentId vs ProjectId

### ISSUE THREAD

**Issue by xantari** [kontent-ai/management-sdk-net#263]
### Motivation

In the https://github.com/kontent-ai/delivery-sdk-net project it appears projectId was renamed to EnvironmentId 

However this project still uses ProjectId. Is there plans to switch to EnvironmentId?

### Proposed solution

Switch to EnvironmentId to bring inline with Delivery SDK

See https://github.com/kontent-ai/delivery-sdk-net/pull/390

**Comment by pokornyd** [comment]
hello Xantari. the switch from ProjectId to EnvironmentId has been included in the[ latest release 6.0.0](https://github.com/kontent-ai/management-sdk-net/releases/tag/6.0.0), among other improvements.
